name: Lint

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.1

      - name: prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          file_pattern: '**/*.{js,md,yaml}'
          prettier_options: --check --config .prettierrc.yml
          github_token: ${{secrets.GH_PAT}}
